backend:
  name: github
  repo: tyskie1000-ux/jewelry
  branch: main
  base_url: https://jewelry-gatekeeper.tyskie1000.workers.dev

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Produkty"
    folder: "content/products"
    extension: "json"
    format: "json"
    create: true
    slug: "{{slug}}"
    
    view_groups:
      - label: "Grupuj wg kategorii"
        field: "category"
    view_filters:
      - label: "Tylko Naszyjniki"
        field: "category"
        pattern: "Naszyjniki"
      - label: "Tylko Bransoletki"
        field: "category"
        pattern: "Bransoletki"
      - label: "Tylko Kolczyki"
        field: "category"
        pattern: "Kolczyki"

    fields:
      - label: "Nazwa produktu"
        name: "title"
        widget: "string"
      - label: "Cena (sama liczba)"
        name: "price"
        widget: "string"
      - label: "Czy pokazać napis NOWOŚĆ?"
        name: "is_new"
        widget: "boolean"
        default: false
      - label: "Opis"
        name: "body"
        widget: "markdown"
      - label: "Zdjęcie główne"
        name: "image"
        widget: "image"
      - label: "Dodatkowe zdjęcia"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image_path}}"
        field: { label: "Wybierz zdjęcie", name: "image_path", widget: "image" }
      - label: "Kategoria"
        name: "category"
        widget: "select"
        options: ["Naszyjniki", "Bransoletki", "Kolczyki"]
